resolver: nightly-2023-01-06
# nightly-2023-01-06
# lts-18.22

packages:
- '.'

extra-deps:
- proteaaudio-0.9.2

flags: {}

extra-package-dbs: []

build:
  library-profiling: false
  executable-profiling: false

allow-newer: true
# rebuild-ghc-options: true
